<a href="https://colab.research.google.com/github/ai7dnn/2026-1-BDA/blob/main/code/06w_dataframe_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

dates = pd.date_range("20260408", periods=6)
dates

DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
               '2026-04-12', '2026-04-13'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
dates = pd.date_range("20260408", end= "20260420")
dates

DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
               '2026-04-12', '2026-04-13', '2026-04-14', '2026-04-15',
               '2026-04-16', '2026-04-17', '2026-04-18', '2026-04-19',
               '2026-04-20'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df2 = pd.DataFrame({
        "A": 1.0,
        "B": pd.Timestamp("20260302"),
        "C": pd.Series(np.arange(1, 3, .5)),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo"
      })
df2

     A          B    C  D      E    F
0  1.0 2026-03-02  1.0  3   test  foo
1  1.0 2026-03-02  1.5  3  train  foo
2  1.0 2026-03-02  2.0  3   test  foo
3  1.0 2026-03-02  2.5  3  train  foo

In [ ]:
df3 = pd.DataFrame({
        "A": 2.0,
        "B": pd.Timestamp("20260302"),
        "C": pd.Series(np.arange(1, 3, .5)),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo"
      })
df3

     A          B    C  D      E    F
0  2.0 2026-03-02  1.0  3   test  foo
1  2.0 2026-03-02  1.5  3  train  foo
2  2.0 2026-03-02  2.0  3   test  foo
3  2.0 2026-03-02  2.5  3  train  foo

In [ ]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
pf['중간']

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [ ]:
pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [ ]:
pf.loc['강수희']

중간    18
기말    27
과제    10
출석    20
Name: 강수희, dtype: int64

In [ ]:
pf.loc[['강수희']]

     중간  기말  과제  출석
강수희  18  27  10  20

In [ ]:
pf.loc[['강수희', '신수빈']]

     중간  기말  과제  출석
강수희  18  27  10  20
신수빈  22  34   8  16

In [ ]:
pf[pf.기말 > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
pf.query('기말 > 20')

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
point = 20
pf.query('기말 > @point')

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
point = 20
pf.query(f'기말 > {point}')

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
pf.loc[pf.index[0], pf.columns[1:]]

기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [ ]:
pf.loc[:, "출석"]

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [ ]:
type(pf.loc[:, "출석"])

pandas.core.series.Series

In [ ]:
ddf = pf.loc[:, "출석"]
type(ddf)

pandas.core.series.Series

In [ ]:
ddf = pf.loc[:, ["출석"]]
type(ddf)

pandas.core.frame.DataFrame

In [ ]:
pf.loc[:, pf.columns[1:]]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [ ]:
pf.loc[:, pf.columns[1:]] [['기말', '과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [ ]:
pf2 = pf.loc[:, pf.columns[1:]]
pf2[['기말', '과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [ ]:
pf3 = pf.iloc[:, 1:]
pf3[['기말', '과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [ ]:
ai = pd.Series([88, 78, 99, 65])
db = pd.Series([73, 67, 98, 99])
pl = pd.Series([46, 87, 78, 87])
df = pd.DataFrame({'AI': ai, 'DB': db, 'PL': pl})
df.index = list('ABCD')
df

   AI  DB  PL
A  88  73  46
B  78  67  87
C  99  98  78
D  65  99  87

In [ ]:
import pandas as pd

df = pd.read_csv('2016년졸음운전.csv',
                 encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [ ]:
df.dtypes.iloc[0]

dtype('int64')

In [ ]:
type(df.dtypes)

pandas.core.series.Series

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [ ]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [ ]:
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

In [ ]:
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [ ]:
df.cumsum()

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [ ]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [ ]:
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [ ]:
from IPython.display import display_html
def display_side_by_side(*args):
    """여러 데이터프레임 비교가 쉽게 옆쪽으로 표시한다"""
    html_str=''
    for df in args:
        html_str += df.to_html() + '&nbsp;'*4
    display_html(html_str.replace('table','table style="display:inline"'), raw=True)

In [ ]:
display_side_by_side(df, df.cumsum(axis=1))

,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,5,387
2016년2월,174,6,328
2016년3월,217,7,435
2016년4월,216,7,419
2016년5월,239,13,522
2016년6월,200,12,362
2016년7월,227,9,460
2016년8월,230,7,490
2016년9월,187,13,347
2016년10월,183,10,367
2016년11월,200,5,418
2016년12월,168,4,364
,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,197,584
2016년2월,174,180,508
2016년3월,217,224,659
2016년4월,216,223,642
2016년5월,239,252,774
2016년6월,200,212,574
2016년7월,227,236,696
2016년8월,230,237,727
2016년9월,187,200,547
2016년10월,183,193,560
2016년11월,200,205,623
2016년12월,168,172,536

In [ ]:
display_side_by_side(df, df.cumsum(axis=0))

,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,5,387
2016년2월,174,6,328
2016년3월,217,7,435
2016년4월,216,7,419
2016년5월,239,13,522
2016년6월,200,12,362
2016년7월,227,9,460
2016년8월,230,7,490
2016년9월,187,13,347
2016년10월,183,10,367
2016년11월,200,5,418
2016년12월,168,4,364
,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,5,387
2016년2월,366,11,715
2016년3월,583,18,1150
2016년4월,799,25,1569
2016년5월,1038,38,2091
2016년6월,1238,50,2453
2016년7월,1465,59,2913
2016년8월,1695,66,3403
2016년9월,1882,79,3750
2016년10월,2065,89,4117
2016년11월,2265,94,4535
2016년12월,2433,98,4899

In [ ]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [ ]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [ ]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [ ]:
display_side_by_side(df, df.mean(axis=1).to_frame())

In [ ]:
display_side_by_side(df, df.max(axis=1).to_frame())

In [ ]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [ ]:
display_side_by_side(df, df2)

In [ ]:
df2.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
재해자수     4997
dtype: int64

In [ ]:
df2.loc['총계'] = df2.sum()
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

In [ ]:
df = pd.DataFrame({'A': range(1, 6),
                   'B': range(6, -3, -2),
                   'C': range(10, 5, -1),
                   'D clmns': range(3, -2, -1),
                   'E': ['python', 'java', 'python', 'go', 'python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query('A > 3 | B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query('A > 3 or B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query('A > 2 & C < 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query('A > 2 and C < 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query("E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
df.query("E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python