<a href="https://colab.research.google.com/github/ai7dnn/2026-1-BDA/blob/main/code/08w_Pandas_Cheat_Sheet_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas Data Wrangling Cheat Sheet

> http://pandas.pydata.org  
> Based on the official Pandas cheat sheet by Irv Lustig, Princeton Consultants

## 0. Setup

In [1]:
import pandas as pd
import numpy as np

# 출력 설정
pd.options.display.max_rows = 20
pd.options.display.max_columns = 10
pd.options.display.precision = 2

## 1. Creating DataFrames

In [2]:
# 각 컬럼 값으로 생성
df = pd.DataFrame(
    {"a": [4, 5, 6],
     "b": [7, 8, 9],
     "c": [10, 11, 12]},
    index=[1, 2, 3])
print(df)

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [18]:
df

   mpg name
0   18    a
1   21    b
2   25    c
3   15    d

In [3]:
# 각 행 값으로 생성
df = pd.DataFrame(
    [[4, 7, 10],
     [5, 8, 11],
     [6, 9, 12]],
    index=[1, 2, 3],
    columns=["a", "b", "c"])
print(df)

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [4]:
# MultiIndex로 생성
df_multi = pd.DataFrame(
    {"a": [4, 5, 6],
     "b": [7, 8, 9],
     "c": [10, 11, 12]},
    index=pd.MultiIndex.from_tuples(
        [("d", 1), ("d", 2), ("e", 2)],
        names=["n", "v"]))
print(df_multi)

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

## 2. Reshaping Data – 레이아웃 변경, 정렬, 인덱싱, 이름 변경

In [ ]:
df = pd.DataFrame({"a": [4,5,6], "b": [7,8,9], "c": [10,11,12]}, index=[1,2,3])

# Melt: 컬럼 → 행
melted = pd.melt(df)
print(melted)

  variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [ ]:
# Pivot: 행 → 컬럼
pivoted = melted.pivot(columns="variable", values="value")
print(pivoted)

In [5]:
df1 = pd.DataFrame({"a": [1, 2]})
df2 = pd.DataFrame({"a": [3, 4]})

# concat: 행 방향으로 붙이기
print(pd.concat([df1, df2]))

   a
0  1
1  2
0  3
1  4

In [6]:
df1 = pd.DataFrame({"a": [1, 2]})
df2 = pd.DataFrame({"b": [3, 4]})

# concat: 컬럼 방향으로 붙이기
print(pd.concat([df1, df2], axis=1))

   a  b
0  1  3
1  2  4

In [9]:
s1 = pd.Series([1, 2], name="a")
s2 = pd.Series([3, 4], name="b")

# concat: 컬럼 방향으로 붙이기
print(pd.concat([s1, s2], axis=1))

   a  b
0  1  3
1  2  4

In [10]:
df = pd.DataFrame({"mpg": [18, 21, 25, 15], "name": ["a","b","c","d"]})
df

   mpg name
0   18    a
1   21    b
2   25    c
3   15    d

In [11]:
df.mpg.sort_values()

3    15
0    18
1    21
2    25
Name: mpg, dtype: int64

In [12]:
# 정렬
print(df.sort_values(by="mpg"))                        # 오름차순

   mpg name
3   15    d
0   18    a
1   21    b
2   25    c

In [13]:
# 정렬
print(df.sort_values("mpg"))                        # 오름차순

   mpg name
3   15    d
0   18    a
1   21    b
2   25    c

In [14]:
print(df.sort_values("mpg", ascending=False))       # 내림차순

   mpg name
2   25    c
1   21    b
0   18    a
3   15    d

In [15]:
print(df.rename(columns={"mpg": "miles_per_gallon"}))  # 컬럼명 변경

   miles_per_gallon name
0                18    a
1                21    b
2                25    c
3                15    d

In [19]:
print(df.sort_index())                              # 인덱스 정렬

   mpg name
0   18    a
1   21    b
2   25    c
3   15    d

In [20]:
print(df.reset_index())                             # 인덱스 초기화

   index  mpg name
0      0   18    a
1      1   21    b
2      2   25    c
3      3   15    d

In [ ]:
print(df.drop(columns=["name"]))                    # 컬럼 삭제

   mpg
0   18
1   21
2   25
3   15

## 3. Method Chaining – 메서드 연결

In [21]:
df = pd.DataFrame({"a": [4,5,6], "b": [700,8,900], "c": [10,11,12]}, index=[1,2,3])
df

   a    b   c
1  4  700  10
2  5    8  11
3  6  900  12

In [22]:
result = (pd.melt(df)
    .rename(columns={"variable": "var", "value": "val"})
    .query("val >= 200"))
print(result)

  var  val
3   b  700
5   b  900

In [24]:
result = pd.melt(df) \
           .rename(columns={"variable": "var", "value": "val"}) \
           .query("val >= 200")
print(result)

  var  val
3   b  700
5   b  900

## 4. 행(Rows) 서브셋

In [28]:
df = pd.DataFrame({
    "Length": [5, 8, 3, 9, 7, 5],
    "Width":  [2, 6, 1, 4, 3, 2],
    "Name":   ["abc","xyz","abcdef","pqr","abcxyz", "abc"]})
df

   Length  Width    Name
0       5      2     abc
1       8      6     xyz
2       3      1  abcdef
3       9      4     pqr
4       7      3  abcxyz
5       5      2     abc

In [29]:
print(df[df.Length > 7])             # 조건으로 행 추출

   Length  Width Name
1       8      6  xyz
3       9      4  pqr

In [30]:
print(df.drop_duplicates())          # 중복 제거

   Length  Width    Name
0       5      2     abc
1       8      6     xyz
2       3      1  abcdef
3       9      4     pqr
4       7      3  abcxyz

In [31]:
print(df.sample(frac=0.5, random_state=1))  # 비율로 무작위 샘플

   Length  Width    Name
2       3      1  abcdef
1       8      6     xyz
4       7      3  abcxyz

In [32]:
print(df.sample(n=2, random_state=1))       # n개 무작위 샘플

   Length  Width    Name
2       3      1  abcdef
1       8      6     xyz

In [33]:
print(df.nlargest(2, "Length"))      # 상위 n개

   Length  Width Name
3       9      4  pqr
1       8      6  xyz

In [34]:
print(df.nsmallest(2, "Length"))     # 하위 n개

   Length  Width    Name
2       3      1  abcdef
0       5      2     abc

In [35]:
print(df.head(3))                    # 처음 n행

   Length  Width    Name
0       5      2     abc
1       8      6     xyz
2       3      1  abcdef

In [36]:
print(df.tail(2))                    # 마지막 n행

   Length  Width    Name
4       7      3  abcxyz
5       5      2     abc

## 5. 컬럼(Columns) 서브셋

In [37]:
df = pd.DataFrame({
    "width":   [1,2,3],
    "length":  [4,5,6],
    "species": ["a","b","c"],
    "x1": [7,8,9], "x2": [10,11,12],
    "x3": [13,14,15], "x4": [16,17,18], "x5": [19,20,21]})
df

   width  length species  x1  x2  x3  x4  x5
0      1       4       a   7  10  13  16  19
1      2       5       b   8  11  14  17  20
2      3       6       c   9  12  15  18  21

In [38]:
print(df[["width", "length", "species"]])   # 여러 컬럼 선택

   width  length species
0      1       4       a
1      2       5       b
2      3       6       c

In [39]:
print(df["width"])                          # 단일 컬럼

0    1
1    2
2    3
Name: width, dtype: int64

In [40]:
print(df.filter(regex="^x[1-5]$"))          # 정규식으로 컬럼 필터

   x1  x2  x3  x4  x5
0   7  10  13  16  19
1   8  11  14  17  20
2   9  12  15  18  21

## 6. 행+컬럼 동시 서브셋 (loc / iloc)

In [43]:
df = pd.DataFrame(np.arange(100).reshape(20, 5),
                   columns=["a","b","c","d","e"])
print(df)

     a   b   c   d   e
0    0   1   2   3   4
1    5   6   7   8   9
2   10  11  12  13  14
3   15  16  17  18  19
4   20  21  22  23  24
5   25  26  27  28  29
6   30  31  32  33  34
7   35  36  37  38  39
8   40  41  42  43  44
9   45  46  47  48  49
10  50  51  52  53  54
11  55  56  57  58  59
12  60  61  62  63  64
13  65  66  67  68  69
14  70  71  72  73  74
15  75  76  77  78  79
16  80  81  82  83  84
17  85  86  87  88  89
18  90  91  92  93  94
19  95  96  97  98  99

In [44]:
print(df.iloc[10:20])             # 행 인덱스 10~19

     a   b   c   d   e
10  50  51  52  53  54
11  55  56  57  58  59
12  60  61  62  63  64
13  65  66  67  68  69
14  70  71  72  73  74
15  75  76  77  78  79
16  80  81  82  83  84
17  85  86  87  88  89
18  90  91  92  93  94
19  95  96  97  98  99

In [45]:
print(df.iloc[:, [1, 2, 4]])      # 위치 1,2,4 컬럼

     b   c   e
0    1   2   4
1    6   7   9
2   11  12  14
3   16  17  19
4   21  22  24
5   26  27  29
6   31  32  34
7   36  37  39
8   41  42  44
9   46  47  49
10  51  52  54
11  56  57  59
12  61  62  64
13  66  67  69
14  71  72  74
15  76  77  79
16  81  82  84
17  86  87  89
18  91  92  94
19  96  97  99

In [46]:
print(df.loc[:, "b":"d"])         # b~d 컬럼 (포함)

     b   c   d
0    1   2   3
1    6   7   8
2   11  12  13
3   16  17  18
4   21  22  23
5   26  27  28
6   31  32  33
7   36  37  38
8   41  42  43
9   46  47  48
10  51  52  53
11  56  57  58
12  61  62  63
13  66  67  68
14  71  72  73
15  76  77  78
16  81  82  83
17  86  87  88
18  91  92  93
19  96  97  98

In [47]:
print(df.loc[df["a"] > 50, ["a","c"]])  # 조건 행 + 특정 컬럼

     a   c
11  55  57
12  60  62
13  65  67
14  70  72
15  75  77
16  80  82
17  85  87
18  90  92
19  95  97

In [48]:
print(df.iat[1, 2])               # 단일값 – 인덱스

7

In [49]:
print(df.at[4, "a"])              # 단일값 – 레이블

20

## 7. query() 사용

In [50]:
df = pd.DataFrame({
    "Length": [5,8,3,9,7],
    "Width":  [2,6,1,4,3],
    "Name":   ["abc","xyz","abcdef","pqr","abcxyz"]})
df

   Length  Width    Name
0       5      2     abc
1       8      6     xyz
2       3      1  abcdef
3       9      4     pqr
4       7      3  abcxyz

In [51]:
print(df.query("Length > 7"))
print(df.query("Length > 5 and Width < 5"))
print(df.query('Name.str.startswith("abc")', engine="python"))

   Length  Width Name
1       8      6  xyz
3       9      4  pqr
   Length  Width    Name
3       9      4     pqr
4       7      3  abcxyz
   Length  Width    Name
0       5      2     abc
2       3      1  abcdef
4       7      3  abcxyz

In [53]:
print(df.query('Name.str.startswith("abc")'))

   Length  Width    Name
0       5      2     abc
2       3      1  abcdef
4       7      3  abcxyz

## 8. 데이터 요약 (Summarize)

In [ ]:
df = pd.DataFrame({
    "w": ["a","b","a","c","b","a"],
    "x": [1,2,3,4,5,6],
    "y": [10.0, 20.5, 30.1, 40.8, 50.2, 60.9]})
df

   w  x     y
0  a  1  10.0
1  b  2  20.5
2  a  3  30.1
3  c  4  40.8
4  b  5  50.2
5  a  6  60.9

In [ ]:
print(df["w"].value_counts())    # 고유값 개수

w
a    3
b    2
c    1
Name: count, dtype: int64

In [ ]:
print(len(df))                   # 행 수

6

In [ ]:
print(df.shape)                  # (행, 컬럼)

(6, 3)

In [ ]:
print(df["w"].nunique())         # 컬럼 내 고유값 수

3

In [ ]:
print(df.describe())             # 기술 통계

          x      y
count  6.00   6.00
mean   3.50  35.42
std    1.87  18.94
min    1.00  10.00
25%    2.25  22.90
50%    3.50  35.45
75%    4.75  47.85
max    6.00  60.90

In [ ]:
print(df.describe(include='all'))             # 기술 통계

          w     x      y
count     6  6.00   6.00
unique    3   NaN    NaN
top       a   NaN    NaN
freq      3   NaN    NaN
mean    NaN  3.50  35.42
std     NaN  1.87  18.94
min     NaN  1.00  10.00
25%     NaN  2.25  22.90
50%     NaN  3.50  35.45
75%     NaN  4.75  47.85
max     NaN  6.00  60.90

In [ ]:
print(df.info())                 # 간략 요약

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   w       6 non-null      object
 1   x       6 non-null      int64
 2   y       6 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 276.0+ bytes
None

In [ ]:
print(df.dtypes)                 # 데이터 타입

w     object
x      int64
y    float64
dtype: object

In [ ]:
# 집계 함수 예시
print(df["y"].sum())
print(df["y"].mean())
print(df["y"].median())
print(df["y"].min(), df["y"].max())
print(df["y"].std(), df["y"].var())
print(df["y"].count())
print(df["y"].quantile([0.25, 0.75]))
print(df["y"].apply(lambda x: x**2))

## 9. 그룹 데이터 (GroupBy)

In [ ]:
df = pd.DataFrame({
    "col":   ["A","B","A","B","A"],
    "value": [10, 20, 30, 40, 50]})

grp = df.groupby(by="col")
print(grp.size())
print(grp.sum())
print(grp.mean())
print(grp.agg(["min","max","mean"]))

In [ ]:
# GroupBy 내 순위/이동 함수
df = pd.DataFrame({"col": ["A","A","B","B"], "val": [3,1,4,2]})
df["rank_dense"]  = df.groupby("col")["val"].rank(method="dense")
df["rank_min"]    = df.groupby("col")["val"].rank(method="min")
df["rank_pct"]    = df.groupby("col")["val"].rank(pct=True)
df["rank_first"]  = df.groupby("col")["val"].rank(method="first")
df["shift_1"]     = df.groupby("col")["val"].shift(1)
df["shift_m1"]    = df.groupby("col")["val"].shift(-1)
df["cumsum"]      = df.groupby("col")["val"].cumsum()
print(df)

## 10. 새 컬럼 생성

In [ ]:
df = pd.DataFrame({
    "Length": [3, 5, 7],
    "Height": [2, 4, 6],
    "Depth":  [1, 2, 3]})

df = df.assign(Area=lambda d: d.Length * d.Height)
df["Volume"] = df.Length * df.Height * df.Depth
df["Bucket"] = pd.qcut(df.Length, q=2, labels=False)
print(df)

## 11. 결측값 처리

In [ ]:
df = pd.DataFrame({
    "a": [1, None, 3],
    "b": [None, 5, None],
    "c": [7, 8, 9]})

print(df.dropna())            # NA 있는 행 삭제
print(df.fillna(0))           # NA를 0으로 채우기
print(pd.isnull(df))          # NA 여부 확인
print(pd.notnull(df))         # 비NA 여부 확인

## 12. 데이터 합치기 (Joins)

In [ ]:
adf = pd.DataFrame({"x1": ["A","B","C"], "x2": [1,2,3]})
bdf = pd.DataFrame({"x1": ["A","B","D"], "x3": ["T","F","T"]})

print("Left Join:")
print(pd.merge(adf, bdf, how="left",  on="x1"))

print("Right Join:")
print(pd.merge(adf, bdf, how="right", on="x1"))

print("Inner Join:")
print(pd.merge(adf, bdf, how="inner", on="x1"))

print("Outer Join:")
print(pd.merge(adf, bdf, how="outer", on="x1"))

In [ ]:
# Filtering Joins
print("adf에서 bdf에 있는 x1 행:")
print(adf[adf.x1.isin(bdf.x1)])

print("adf에서 bdf에 없는 x1 행:")
print(adf[~adf.x1.isin(bdf.x1)])

In [ ]:
# Set-like Operations
ydf = pd.DataFrame({"x1":["A","B","C"], "x2":[1,2,3]})
zdf = pd.DataFrame({"x1":["B","C","D"], "x2":[2,3,4]})

print("교집합(Intersection):")
print(pd.merge(ydf, zdf))

print("합집합(Union):")
print(pd.merge(ydf, zdf, how="outer"))

print("차집합(Setdiff - ydf only):")
print(
    pd.merge(ydf, zdf, how="outer", indicator=True)
    .query('_merge == "left_only"')
    .drop(columns=["_merge"])
)

## 13. 윈도우 함수 (Windows)

In [ ]:
df = pd.DataFrame({"val": [1, 2, 3, 4, 5, 6]})

df["expanding_sum"] = df["val"].expanding().sum()
df["rolling_mean3"] = df["val"].rolling(3).mean()
df["cumsum"]  = df["val"].cumsum()
df["cummax"]  = df["val"].cummax()
df["cummin"]  = df["val"].cummin()
df["cumprod"] = df["val"].cumprod()
print(df)

## 14. 타입 변환 (Changing Type)

In [ ]:
df = pd.DataFrame({
    "num_str":  ["1","2","3"],
    "date_str": ["2024-01-01","2024-06-15","2024-12-31"],
    "category": ["a","b","a"]})

df["num"]      = pd.to_numeric(df["num_str"])
df["date"]     = pd.to_datetime(df["date_str"])
df["category"] = df["category"].astype("category")
print(df.dtypes)
print(df)

## 15. Datetime 속성

In [ ]:
s = pd.to_datetime(pd.Series(["2024-03-15", "2025-11-30", "2026-07-04"]))
df = pd.DataFrame({"date": s})
df["year"]    = df["date"].dt.year
df["month"]   = df["date"].dt.month
df["day"]     = df["date"].dt.day
df["hour"]    = df["date"].dt.hour
df["minute"]  = df["date"].dt.minute
df["second"]  = df["date"].dt.second
df["quarter"] = df["date"].dt.quarter
print(df)

## 16. 문자열 연산 (Series.str)

In [ ]:
s = pd.Series(["Hello World", "pandas library", "Data Science"])

print(s.str.count("a"))           # 'a' 개수
print(s.str.len())                # 문자열 길이
print(s.str.upper())              # 대문자
print(s.str.lower())              # 소문자
print(s.str.title())              # 단어 첫글자 대문자
print(s.str.replace("a","@"))     # 치환
print(s.str.slice(0, 5))          # 슬라이싱
print(s.str.split(" ").str.get(0))  # 분리 후 첫 단어
print(s.str.join("-"))            # 비워두면 에러, 리스트 원소 연결용
print(s.str.isalnum())            # 영숫자 여부

## 17. Mapping / Apply

In [ ]:
s = pd.Series([1, 2, 3, 4, 5])
print(s.map(lambda x: x * 2))

df = pd.DataFrame({"a": [1,2,3], "b": [4,5,6]})
print(df.apply(lambda s: s.max() - s.min(), axis=1))

## 18. 시각화 (Plotting)

> matplotlib 백엔드를 사용합니다.

In [ ]:
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

df = pd.DataFrame({
    "x": range(10),
    "y": [i**2 for i in range(10)],
    "z": [i*3 for i in range(10)]})

fig, axes = plt.subplots(2, 3, figsize=(14, 8))

df.plot(x="x", y="y", ax=axes[0,0], title="Line")
df.plot.scatter(x="x", y="y", ax=axes[0,1], title="Scatter")
df[["y","z"]].plot.hist(ax=axes[0,2], bins=5, title="Histogram", alpha=0.7)
df[["y","z"]].plot.bar(ax=axes[1,0], title="Bar")
df[["y","z"]].plot.area(ax=axes[1,1], title="Area", alpha=0.5)
df[["y","z"]].plot.box(ax=axes[1,2], title="Boxplot")

plt.tight_layout()
plt.savefig("pandas_plots.png", dpi=100)
plt.show()
print("저장 완료: pandas_plots.png")

## 19. 입출력 (Input/Output)

In [ ]:
df = pd.DataFrame({"a":[1,2,3], "b":[4,5,6]})

# CSV
df.to_csv("sample.csv", index=False)
df_csv = pd.read_csv("sample.csv")
print(df_csv)

# Excel
df.to_excel("sample.xlsx", index=False)
df_excel = pd.read_excel("sample.xlsx")
print(df_excel)

# Parquet (pyarrow 필요)
try:
    df.to_parquet("sample.parquet")
    df_parquet = pd.read_parquet("sample.parquet")
    print(df_parquet)
except Exception as e:
    print(f"Parquet 저장/읽기: {e}")

## 20. 자주 쓰는 옵션 (Frequently Used Options)

In [ ]:
# 현재 값 조회
print(pd.get_option("display.max_rows"))
print(pd.get_option("display.max_columns"))

# 값 설정
pd.set_option("display.max_rows", 50)
pd.set_option("display.precision", 3)

# 설명 보기
pd.describe_option("display.max_rows")

# 기본값으로 초기화
pd.reset_option("display.max_rows")
pd.reset_option("display.precision")
print("옵션 초기화 완료")

---

## ✅ 완료!

Pandas Cheat Sheet의 모든 주요 기능을 다루었습니다.

| 섹션 | 내용 |
|---|---|
| 1 | DataFrame 생성 |
| 2 | 데이터 재구조화 |
| 3 | 메서드 체이닝 |
| 4~6 | 서브셋 선택 |
| 7 | query() |
| 8 | 요약 통계 |
| 9 | GroupBy |
| 10 | 새 컬럼 생성 |
| 11 | 결측값 처리 |
| 12 | 데이터 병합 |
| 13 | 윈도우 함수 |
| 14~16 | 타입·날짜·문자열 |
| 17 | Mapping/Apply |
| 18 | 시각화 |
| 19 | 입출력 |
| 20 | 옵션 관리 |